import comp from "C:/code_V5.0/clone/md_code_hope/src/.vuepress/.temp/pages/issue/vuepress代码块切换语言.html.vue"
const data = JSON.parse("{\"path\":\"/issue/vuepress%E4%BB%A3%E7%A0%81%E5%9D%97%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80.html\",\"title\":\"代码块之间的标签切换功能\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2024-09-02T00:00:00.000Z\",\"category\":\"VuePress\",\"tag\":[\"VuePress\",\"网站搭建\"],\"description\":\"代码块之间的标签切换功能 在 VuePress 中，你可以通过使用内置的代码块语法来展示代码，并且支持代码块之间的标签切换功能，从而让用户可以在不同的编程语言之间切换。这个功能通常通过使用 VuePress 的内置插件或自定义插件来实现。 以下是实现代码块切换功能的步骤： 1. 使用内置的 tabs 插件 VuePress 默认没有直接内置的代码块切换...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"代码块之间的标签切换功能\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-09-02T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"menherachan\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://laffey4590.asia/issue/vuepress%E4%BB%A3%E7%A0%81%E5%9D%97%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"基于vuepress的网站\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"代码块之间的标签切换功能\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"代码块之间的标签切换功能 在 VuePress 中，你可以通过使用内置的代码块语法来展示代码，并且支持代码块之间的标签切换功能，从而让用户可以在不同的编程语言之间切换。这个功能通常通过使用 VuePress 的内置插件或自定义插件来实现。 以下是实现代码块切换功能的步骤： 1. 使用内置的 tabs 插件 VuePress 默认没有直接内置的代码块切换...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"网站搭建\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"VuePress\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-09-02T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":1.88,\"words\":563},\"filePathRelative\":\"issue/vuepress代码块切换语言.md\",\"excerpt\":\"\\n<p>在 VuePress 中，你可以通过使用内置的代码块语法来展示代码，并且支持代码块之间的标签切换功能，从而让用户可以在不同的编程语言之间切换。这个功能通常通过使用 VuePress 的内置插件或自定义插件来实现。</p>\\n<p>以下是实现代码块切换功能的步骤：</p>\\n<h3>1. 使用内置的 <code>tabs</code> 插件</h3>\\n<p>VuePress 默认没有直接内置的代码块切换功能，但你可以通过一些插件来实现这种效果。其中一个常用的插件是 <code>@vuepress/plugin-tabs</code>。</p>\\n<h4>安装插件</h4>\\n<div class=\\\"language-bash line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"bash\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code class=\\\"language-bash\\\"><span class=\\\"line\\\"><span style=\\\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\\\">npm</span><span style=\\\"--shiki-light:#50A14F;--shiki-dark:#98C379\\\"> install</span><span style=\\\"--shiki-light:#50A14F;--shiki-dark:#98C379\\\"> @vuepress/plugin-tabs</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
